<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinalYearProject.Api\FinalYearProject.Api.csproj" />
    <ProjectReference Include="..\FinalYearProject.Shared\FinalYearProject.Shared.csproj" />
  </ItemGroup>

</Project>
