<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />
    <PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.31" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinalYearProject.Services\FinalYearProject.Services.csproj" />
    <ProjectReference Include="..\FinalYearProject.Shared\FinalYearProject.Shared.csproj" />
  </ItemGroup>

</Project>
