<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bbfda06d-6325-409a-991a-5e43b9e8b99b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\**" />
    <Content Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
    <_WebToolingArtifacts Remove="Properties\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinalYearProject.AccuracyAnalysis\FinalYearProject.Accuracy.Analysis.csproj" />
    <ProjectReference Include="..\FinalYearProject.Audio\FinalYearProject.Audio.csproj" />
    <ProjectReference Include="..\FinalYearProject.EfCore\FinalYearProject.EfCore.csproj" />
    <ProjectReference Include="..\FinalYearProject.Shared\FinalYearProject.Shared.csproj" />
  </ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="FinalYearProject.Integration.Tests" />
	</ItemGroup>

</Project>
